const PedidoModel = () => ({
  idpedido : '',
  idofertas: '',
  nomeoferta: '',
  valoroferta: '',
  metodopagamento: '',
  datadecriacao: '',
  datademodificacao: '',
  idnegocio: '',
  nomenegocio: '',
  devicetokenuser: '',
  devicetokennegocio: '',
  cpfnanota: '',
  cpf: '',
  valortotal: '',
  valorentrega: '',
  troco: '',
  observacao: '',
  espec: '',
  qntositems: '',
  contatouser: '',
  receberviawpp: '',
  iduser: '',
  nomeuser: '',
  bairro: '',
  endereco: '',
  numeroendereco: '',
  complemento: '',
  app: '',
  actionStatus: '',
  TypeCompra: '',
  CestinhaPreco: ''

})

export default PedidoModel
